### ISSUE TITLE
Breaking from iteration hangs

### ISSUE THREAD

**Issue by drtconway** [Stieneee/simple-zstd#12]
Hi

Great library, thanks for contributing.

This might be me being naive; apologies if so.

I want to uncompress a large text file on the fly, and I have different phases in the code (i.e. the file starts with metadata lines which I want to read all of, then data lines, which I want to expose as an async iterator. However, I'm at a simpler point so far.

When I run the following code in Mocha, it succeeds, but then hangs. If I take out the `break` it works just fine.

```
import * as readline from "readline";
import * as fs from "fs";
import * as path from "path";
import { ZSTDDecompressMaybe } from "simple-zstd";

it("process actual lines", async () => {
  console.log(__dirname);
  let filePath = path.join(__dirname, "/data/NA24385.trio.subset.vcf.zst");
  const stream = fs.createReadStream(filePath).pipe(ZSTDDecompressMaybe());
  const lines = readline.createInterface({
    input: stream,
    crlfDelay: Infinity,
  });

  let n = 0;
  for await (const line of lines) {
      n += line.length;
      if (n > 1024*1024) {
          break;
      }
  }
  console.log(n);
});
```

I presume I need to clean up somehow. Is there a better way to do this?

I assume the behaviour doesn't particularly depend on the specific compressed data. My file is 4.4Mb, which is a bit fat for a repro, but if you think it necessary, I can cut it down and see if the behaviour still exists.

**Comment by Stieneee** [comment]
The application is "hanging" because the fs read stream is still open. If your file is actually 4.4 MB and you are breaking the first MB (1024 * 1024).

See the code changes to understand what's happening. I changed the break threshold in my test to make it more clear. I also switched to the pipeline function which I recommend you take a look at.

https://stackoverflow.com/questions/58875655/whats-the-difference-between-pipe-and-pipeline-on-streams

```javascript
  it.only('process actual lines', async () => {
    console.log(__dirname);
    const filePath = path.join(__dirname, '/sample/bigfile.txt.zst');
    const fileStream = fs.createReadStream(filePath);
    fileStream.on('end', () => { console.log('file end'); });
    const decompressProcess = ZSTDDecompressMaybe();
    decompressProcess.on('end', () => console.log('zstd end'));
    const s = stream.pipeline(fileStream, decompressProcess, (err) => {
      if (err) console.log(err);
      else console.log('pipeline complete');
    });

    const lines = readline.createInterface({
      input: s,
      crlfDelay: Infinity,
    });

    let n = 0;
    for await (const line of lines) {
      n += line.length;
      if (n > 100) {
        break;
      }
    }
    console.log(n);
  });
``` 

Without the break my console output is 

```
/home/stieneee/git/standalone/simple-zstd/test
file end
pipeline complete
zstd end
100000000
    ✔ process actual lines (547ms)


  1 passing (549ms)
```

With the break my console output is
```
  Test simple-zstd
/home/stieneee/git/standalone/simple-zstd/test
200
```

If we look at the state of the system you will see that the node process still has the file open and that the child zstd process is running. If you only wanted to read the first x bytes or x lines of the file your could force the file stream closed.

Hope that helps.

**Comment by drtconway** [comment]
Perfect. Thanks.
